// -*- mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
// vi: set et ts=4 sw=4 sts=4:
/*
  This file is part of the eWoms project.

  eWoms is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  eWoms is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with eWoms.  If not, see <http://www.gnu.org/licenses/>.

  Consult the COPYING file in the top-level source directory of this
  module for the precise wording of the license and the list of
  copyright holders.
*/
/*!
 * \file
 *
 * \brief This file includes all specializations for the dense-AD Evaluation class.
 *
 * \attention THIS FILE GETS AUTOMATICALLY GENERATED BY THE "genEvalSpecializations.py"
 *            SCRIPT. DO NOT EDIT IT MANUALLY!
 */
#ifndef EWOMS_DENSEAD_EVALUATION_SPECIALIZATIONS_HH
#define EWOMS_DENSEAD_EVALUATION_SPECIALIZATIONS_HH

#include <ewoms/common/densead/dynamicevaluation.hh>
#include <ewoms/common/densead/evaluation1.hh>
#include <ewoms/common/densead/evaluation2.hh>
#include <ewoms/common/densead/evaluation3.hh>
#include <ewoms/common/densead/evaluation4.hh>
#include <ewoms/common/densead/evaluation5.hh>
#include <ewoms/common/densead/evaluation6.hh>
#include <ewoms/common/densead/evaluation7.hh>
#include <ewoms/common/densead/evaluation8.hh>
#include <ewoms/common/densead/evaluation9.hh>
#include <ewoms/common/densead/evaluation10.hh>
#include <ewoms/common/densead/evaluation11.hh>
#include <ewoms/common/densead/evaluation12.hh>

#endif // EWOMS_DENSEAD_EVALUATION_SPECIALIZATIONS_HH